### ISSUE TITLE
Sync on file change vs file save

### ISSUE THREAD

**Issue by timpish** [remicass/vscode-exts#10]
Thanks for the VSCode extension. Do you know if there's an option to sync on file change vs file save?

**Comment by jeremyrajan** [comment]
@timpish thank you for using the lib. I assume you are taking about `browsersync` :).

I don't think, browsersync supports that option. Let me do some digging and see if I can pass it as workspace config.

Cheers,
Jeremy

**Comment by jeremyrajan** [comment]
Closing this, as it expects a file change. Apologies for that.
