### ISSUE TITLE
VSCode browser sync - how to configure?

### ISSUE THREAD

**Issue by Worie** [remicass/vscode-exts#17]
Hi! Thanks for the extension, seemed quicker than setting up browser sync for some of my projects.

Is there an option to configure the config of browsersync? I'd like to set `notify: false` but i don't know where to look in VSCode to set it up, could you help perhaps?

**Comment by Worie** [comment]
Unfortunately I need a little bit more spare time at the moment as well, if I manage to sit down to it I'll surely create a PR :)

**Comment by jeremyrajan** [comment]
@Worie, added functionality to pass options in this PR, https://github.com/remicass/vscode-exts/pull/24

**Comment by jeremyrajan** [comment]
@Worie `browsersync@2.1.0` should solve your issues 😄!

**Comment by Worie** [comment]
nice! thanks!
