### ISSUE TITLE
webpack overwrites current project dev dependencies without warning...

### ISSUE THREAD

**Issue by melMass** [remicass/vscode-exts#21]
This is a very bad default behaviour it just wiped all my dev dependencies...

**Comment by jeremyrajan** [comment]
@melMass thanks for reporting! Totally overlooked the fact that it was overriding 😢. Should be fixed in this one: https://github.com/remicass/vscode-exts/pull/22

**Comment by jeremyrajan** [comment]
@melMass Please download the latest version `2.0.2`. That should fix this issue 😄!
