### ISSUE TITLE
The Extention does not work for me : June 2017

### ISSUE THREAD

**Issue by ben-pony** [remicass/vscode-exts#6]
' command 'extension.createConfig' not found '

![image](https://user-images.githubusercontent.com/16815028/27723515-296290f4-5d76-11e7-9848-451b725091f0.png)

**Comment by ben-pony** [comment]
i wasnt inside my project directory, once i was it worked.
maybe you`d like to handle this scenario by asking the user to open a src project directory,
cheers ,thank you for the extention 👍

**Comment by jeremyrajan** [comment]
Thanks for pointing out @ben-pony. Hope the ext has helped you.
