### ISSUE TITLE
Not working on Visual Studio Code 64bit Version

### ISSUE THREAD

**Issue by HansS** [remicass/vscode-exts#7]
undefined in webpack.config.js

**Comment by jeremyrajan** [comment]
Hi @HansS, Did you get "undefined" text in webpack.config generated you mean?

Thanks!

**Comment by jeremyrajan** [comment]
hi @HansS,

I have published the latest version v2.0.2. You may update it via vscode extensions. Please let me know, if that fixes it 🙂 .

Thanks!

**Comment by jeremyrajan** [comment]
Closing the issue, since no response. @HansS, please re-open if you see issues :)
